#
# Makefile for xhyp interface
#

//CPPFLAGS_vmlinux.lds := -DTEXT_OFFSET=$(TEXT_OFFSET)
//AFLAGS_head.o        := -DTEXT_OFFSET=$(TEXT_OFFSET)

obj-y	+= hypercalls.o
obj-y	+= early_printk.o
obj-y	+= printch.o
obj-y	+= xhyp.o
obj-y	+= time.o
obj-y	+= console.o
obj-y	+= fault.o

clean:
